### List of all users

GET http://localhost:5000/api/v1/auth/all

### register

POST http://localhost:5000/api/v1/auth/register
content-type: application/json

{
  "firstName": "sohel",
  "lastName": "rana",
  "password": "1",
  "email": "strindsssfsssdfg"
}